node-url = "http://localhost:8545"

[dex]
# Specify which chain to use, 1 for Ethereum.
# More info here: https://www.okx.com/en-au/web3/build/docs/waas/walletapi-resources-supported-networks
chain-id = "1"

# Optionally specify custom OKX Swap API endpoints
# Sell orders endpoint (exactIn mode, uses V6 API by default)
# sell-orders-endpoint = "https://web3.okx.com/api/v6/dex/aggregator/"

# Buy orders endpoint (exactOut mode, uses V5 API, only supports Ethereum, Base, BSC, and Arbitrum chains and only Uni v2 and v3 protocols)
# If not specified, buy orders will be declined.
# buy-orders-endpoint = "https://www.okx.com/api/v5/dex/aggregator/"

# OKX Project ID. Instruction on how to create a project:
# https://www.okx.com/en-au/web3/build/docs/waas/introduction-to-developer-portal-interface#create-project
api-project-id = "$OKX_PROJECT_ID"

# OKX API Key. Instruction on how to generate an API key:
# https://www.okx.com/en-au/web3/build/docs/waas/introduction-to-developer-portal-interface#generate-api-keys
api-key = "$OKX_API_KEY"

# OKX Secret key used for signing request. Instruction on how to get a security token:
# https://www.okx.com/en-au/web3/build/docs/waas/introduction-to-developer-portal-interface#view-the-secret-key
api-secret-key = "$OKX_SECRET_KEY"

# OKX Secret key passphrase. Instruction on how to get a passphrase:
# https://www.okx.com/en-au/web3/build/docs/waas/introduction-to-developer-portal-interface#generate-api-keys
api-passphrase = "$OKX_PASSPHRASE"
